clone:
  git:
    image: rchain/buildenv:latest
    commands: | bash -c '
        set -e
        git clone -b $DRONE_BRANCH $DRONE_REMOTE_URL
        if [[ -n $DRONE_PULL_REQUEST ]]; then
            git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
            git merge --no-edit FETCH_HEAD
        fi
    '

pipeline:
  build:
    image: rchain/buildenv:latest
    commands:
      - env | sort
