clone:
  git:
    image: rchain/buildenv:latest
    commands: |
        set -ex
        git clone -b $DRONE_BRANCH $DRONE_REMOTE_URL .
        if [ x$DRONE_PULL_REQUEST != x ]; then
            git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
            EMAIL=nobody git merge --no-edit FETCH_HEAD
        fi

pipeline:
  build:
    image: rchain/buildenv:latest
    commands:
      - env | sort
